name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: ^1.5.0
  google_sign_in: 5.1.0
  lottie: 1.1.0
  introduction_screen: 2.1.0
  avatar_glow: 2.0.1
  emoji_picker_flutter: 1.0.7
  emoji_keyboard_flutter: 1.1.2
  firebase_auth: 3.1.1
  cloud_firestore: ^2.5.3
  get_storage: 2.0.3
  intl: 0.17.0
  image_picker: 0.8.4+2
  firebase_storage: 10.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

